version: "3.7"
name: "stats"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
  mongo:
    image: mongo:latest
  app:
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ../../..
      dockerfile: .devops/docker/local/Dockerfile
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      PGHOST: postgres
      PGUSER: postgres
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379
    expose:
      - 4000
    volumes:
      - ../../..:/workspaces/stats
    working_dir: /workspaces/stats
